### ISSUE TITLE
Independent ASP

### ISSUE THREAD

**Issue by HenryMiller** [IBM/ibmi-bob#172]
Hello,
I'm using makei cvtsrcpf mylib command  but it can't find the library.
The library actually is on an Independent ASP .
It works fine for libraries on *SYSBAS
Best regards,
Giovanni

**Comment by edmundreinhardt** [comment]
Hello Giovanni,
`make cvtsrcpf` is a PASE command.  You will want to run it in a job with has the SETASPGRP() command run so that the iASP is online and the library can be found.
From PASE you could do
`SETASPGRP(<YOURASP>) && makei cvtsrcpf <SRCPF> <LIBRARY>`
Alternatively you could from 5250 run the SETASPGRP and then `QSH CMD(' /QOpenSys/pkgs/bin/makei cvtsrcpf ...

**Comment by HenryMiller** [comment]
Hello Edmund ,
thank you for your reply.
I'm on V7R4.
Unfortunately both 5250 and PASE environment are still not working and showing same error.
I'm going to copy library outside independent ASP.


This is what I've done.


5250  
-----

From Command line (outside pdm)

SETASPGRP ASPGRP(IASP01)   

then 

QSH CMD('/QOpenSys/pkgs/bin/makei cvtsrcpf QSRC BMS71L_SRC')

Error Message 
   [92m> /QOpenSys/pkgs/lib/bob/scripts/cvtsrcpf QSRC BMS71L_SRC [0m  
  cvtsrcpf: Library BMS71L_SRC doesn't exist.  Exiting.     



          
<img width="317" alt="Screenshot at Nov 22 21-20-46" src="https://user-images.githubusercontent.com/1829995/203413533-cf0c3b84-5cea-45d4-b3ac-bd0cb9c2aad4.png">
